import pybullet as p
from bandu.config import BANDU_ROOT
env_params = dict(
    reward_type="height",
    # urdfs =["parts/urdfs/Colored_Block/Colored_Block.urdf_path",
    #         "parts/urdfs/Skewed Rectangular Prism/Skewed Rectangular Prism.urdf_path",
    #         "parts/urdfs/Pencil/Pencil.urdf_path",
    #         "parts/urdfs/Skewed Cylinder/Skewed Cylinder.urdf_path",
    #         "parts/urdfs/Skewed Triangular Prism/Skewed Triangular Prism.urdf_path",
    #         "parts/urdfs/Skewed Wedge/Skewed Wedge.urdf_path"],
    # stls=["parts/stls/Colored Block.STL",
    #       "parts/stls/Skewed Rectangular Prism.STL",
    #       "parts/stls/Pencil.STL",
    #       "parts/stls/Skewed Cylinder.STL",
    #       "parts/stls/Skewed Triangular Prism.STL",
    #       "parts/stls/Skewed Wedge.STL"],
    # stl_dir="parts/stls/main/bandu_train/",
    # urdf_dir ="parts/urdfs/main/bandu_train/",
    # urdf_dir ="/home/richard/improbable/data/urdfs",
    # stl_dir ="/home/richard/improbable/data/stls",
    # urdf_dir ="/home/richard/data/datasets/engmikedset/urdfs",
    # stl_dir ="/home/richard/data/datasets/engmikedset/stls",
    # urdf_dir ="/home/richard/data/datasets/cmvscvaecm/urdfs",
    # stl_dir ="/home/richard/data/datasets/cmvscvaecm/stls",
    # # urdf_dir ="/home/richard/data/datasets/pca_comparisons/urdfs",
    # stl_dir ="/home/richard/data/datasets/pca_comparisons/stls",
    # stl_dir="/home/richard/data/datasets/foundation_only/stls",
    # urdf_dir="/home/richard/data/datasets/foundation_only/urdfs",
    # urdf_dir ="/home/richard/data/datasets/remedial/urdfs",
    # stl_dir ="/home/richard/data/datasets/remedial/stls",
    # urdf_dir ="/home/richard/data/datasets/symmetric/urdfs",
    # stl_dir ="/home/richard/data/datasets/symmetric/stls",
    # urdf_dir ="/home/richard/data/adversarial/urdfs",
    # stl_dir ="/home/richard/data/adversarial/stls",
    # urdf_dir="/home/richard/data/egg/urdfs",
    # stl_dir="/home/richard/data/egg/stls",
    # stl_dir="parts/stls/main/bandu_val/",
    # urdf_dir ="parts/urdfs/main/bandu_val/",
    # stl_dir="parts/stls/main/engmikedset_train/",
    # urdf_dir ="/home/richard/improbable/spinningup/parts/urdfs/engmikedset1",
    # stl_dir="/home/richard/improbable/spinningup/parts/stls/engmikedset1",
    # urdfs=["/home/richard/improbable/bandu_code/bandu/parts/vertical_urdfs/Skewed Rectangular Prism/Skewed Rectangular Prism.urdf_path"],
    # stls=["/home/richard/improbable/bandu_code/bandu/parts/vertical_stls/Skewed Rectangular Prism.stl"],
    # start_rotation_type="identity",
    urdf_dir = "parts/urdfs/main/engmikedset/",
    stl_dir = "parts/stls/main/engmikedset/",
    start_rotation_type="full",
    urdf_holdout_frac=0, #what percentage of all urdfs to train on
    urdf_holdout_sampling_strategy="block_base",
    phase="train",
    p_connect_type=p.DIRECT,
    num_sub_steps=1,
    forward_sim_steps=2000,
    pointcloud_state=True,
    num_objects=1,
    placement_offset=.1,
    scale_factor=1.5,
    height_offset=.4,
    realtime=0
)